# Generated by Django 4.1.7 on 2023-03-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
