# Generated by Django 4.1.7 on 2023-03-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_remove_blogentry_tags_blogentry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='tags',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
